import {test,after} from 'node:test';
import assert from 'node:assert/strict';
process.env.NODE_ENV='test';process.env.DATA_DIR='memory://';process.env.ADMIN_PASSWORD='TesteSeguro123!';
delete process.env.DATABASE_URL;
const {app,db}=await import('../server.mjs');
const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const base=`http://127.0.0.1:${server.address().port}/api`;let cookie='';
async function request(path,method='GET',body,auth=true){const res=await fetch(base+path,{method,headers:{'Content-Type':'application/json',...(auth?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:res.status,body:await res.json(),cookie:res.headers.get('set-cookie')};}
async function create(table,body){const r=await request('/'+table,'POST',body);assert.equal(r.status,201,JSON.stringify(r.body));return r.body;}
after(async()=>{await new Promise(r=>server.close(r));await db.close();});
test('Fluxos RF01–RF22 e regras de integridade',async t=>{
 await t.test('Autenticação obrigatória, senha derivada e sessão',async()=>{assert.equal((await request('/data')).status,401);assert.equal((await request('/login','POST',{login:'admin',senha:'errada'})).status,401);const login=await request('/login','POST',{login:'admin',senha:'TesteSeguro123!'});assert.equal(login.status,200);cookie=login.cookie.split(';')[0];assert.match(login.cookie,/HttpOnly/);const u=(await db.query('SELECT senha_hash FROM usuario')).rows[0];assert.match(u.senha_hash,/^\$2[aby]\$/);});
 const aluno=await create('aluno',{nome:'Ana Teste',cpf:'123.456.789-01',data_nascimento:'1995-01-31',email:'ana@example.test'});
 const professor=await create('professor',{nome:'Professor Teste',cpf:'23456789012',data_admissao:'2024-01-01'});
 const plano=await create('plano',{nome:'Mensal',valor_mensal:99.9,duracao_meses:1,ativo:true});
 const exercicio=await create('exercicio',{nome:'Agachamento',grupo_muscular:'Pernas'});
 await t.test('CPF normalizado e único; valores positivos e campos obrigatórios',async()=>{assert.equal(aluno.cpf,'12345678901');assert.equal((await request('/aluno','POST',{nome:'Duplicado',cpf:aluno.cpf,data_nascimento:'1990-01-01'})).status,400);assert.equal((await request('/plano','POST',{nome:'Inválido',valor_mensal:0,duracao_meses:1})).status,400);assert.equal((await request('/plano','POST',{nome:'Inválido',valor_mensal:100,duracao_meses:-1})).status,400);assert.equal((await request('/exercicio','POST',{nome:'Sem grupo'})).status,400);});
 await t.test('Presença exige matrícula vigente',async()=>{assert.match((await request('/presenca','POST',{id_aluno:aluno.id_aluno})).body.error,/sem matrícula/);});
 const hoje=(await request('/data')).body.hoje;
 const matricula=await create('matricula',{id_aluno:aluno.id_aluno,id_plano:plano.id_plano,data_inicio:hoje});
 await t.test('Uma matrícula ativa, cálculo de fim, plano inativo e histórico',async()=>{assert.ok(matricula.data_fim>matricula.data_inicio);assert.equal((await request('/matricula','POST',{id_aluno:aluno.id_aluno,id_plano:plano.id_plano,data_inicio:hoje})).status,400);await request('/plano/'+plano.id_plano,'PUT',{ativo:false});assert.match((await request('/matricula','POST',{id_aluno:aluno.id_aluno,id_plano:plano.id_plano,data_inicio:hoje})).body.error,/plano ativo/);assert.equal((await request('/plano/'+plano.id_plano,'DELETE')).status,400);await request('/plano/'+plano.id_plano,'PUT',{ativo:true});});
 await t.test('Presença diária única com horário do servidor',async()=>{const p=await create('presenca',{id_aluno:aluno.id_aluno,data_presenca:'1900-01-01'});assert.equal(p.data_presenca.slice(0,10),hoje);assert.match((await request('/presenca','POST',{id_aluno:aluno.id_aluno})).body.error,/já foi registrada/);});
 const item={id_exercicio:exercicio.id_exercicio,ordem:1,series:3,repeticoes:12,carga_sugerida:20,observacao:'Descanso de 60 s'};
 const ficha=await create('ficha_treino',{id_aluno:aluno.id_aluno,id_professor:professor.id_professor,descricao:'Treino A',exercicios:[item]});
 await t.test('Ficha exige exercício, rejeita duplicidade e desfaz alteração inválida',async()=>{const empty=await request('/ficha_treino','POST',{id_aluno:aluno.id_aluno,id_professor:professor.id_professor,descricao:'Ficha vazia',exercicios:[]});assert.equal(empty.status,400);const update=await request('/ficha_treino/'+ficha.id_ficha,'PUT',{descricao:'Inválida',exercicios:[item,item]});assert.equal(update.status,400);const all=(await request('/data')).body;assert.equal(all.ficha_treino.length,1);assert.equal(all.ficha_treino[0].descricao,'Treino A');assert.equal(all.ficha_exercicio.length,1);const valid=await request('/ficha_treino/'+ficha.id_ficha,'PUT',{descricao:'Treino B',ativa:false,exercicios:[{...item,series:4}]});assert.equal(valid.status,200);assert.equal((await request('/data')).body.ficha_exercicio[0].series,4);});
 await t.test('Exclusões protegem vínculos; ficha remove associação em cascata',async()=>{for(const [table,id]of [['aluno',aluno.id_aluno],['professor',professor.id_professor],['exercicio',exercicio.id_exercicio]])assert.equal((await request('/'+table+'/'+id,'DELETE')).status,400);assert.equal((await request('/ficha_treino/'+ficha.id_ficha,'DELETE')).status,200);assert.equal((await request('/data')).body.ficha_exercicio.length,0);assert.equal((await request('/exercicio/'+exercicio.id_exercicio,'DELETE')).status,200);});
 await t.test('Cancelamento preserva histórico e bloqueia presença',async()=>{assert.equal((await request('/matricula/'+matricula.id_matricula,'PUT',{situacao:'cancelada'})).status,200);assert.match((await request('/presenca','POST',{id_aluno:aluno.id_aluno})).body.error,/sem matrícula/);assert.equal((await request('/data')).body.matricula[0].situacao,'cancelada');});
 await t.test('Fim de mês, vencimento automático e nova matrícula',async()=>{const old=await create('matricula',{id_aluno:aluno.id_aluno,id_plano:plano.id_plano,data_inicio:'2024-01-31'});assert.equal(old.data_fim.slice(0,10),'2024-02-29');assert.equal(old.situacao,'vencida');const fresh=await create('matricula',{id_aluno:aluno.id_aluno,id_plano:plano.id_plano,data_inicio:hoje});await db.query("UPDATE matricula SET data_inicio=CURRENT_DATE-10,data_fim=CURRENT_DATE-1 WHERE id_matricula=$1",[fresh.id_matricula]);const all=(await request('/data')).body;assert.equal(all.matricula.find(m=>m.id_matricula===fresh.id_matricula).situacao,'vencida');await create('matricula',{id_aluno:aluno.id_aluno,id_plano:plano.id_plano,data_inicio:hoje});});
 await t.test('Edição, auditoria, referências obrigatórias e logout',async()=>{assert.equal((await request('/aluno/'+aluno.id_aluno,'PUT',{nome:'Ana Atualizada'})).status,200);const all=(await request('/data')).body;assert.equal(all.aluno[0].nome,'Ana Atualizada');assert.ok(all.aluno[0].atualizado_em);assert.equal((await request('/ficha_treino','POST',{id_aluno:999,id_professor:professor.id_professor,descricao:'Inválida'})).status,400);assert.equal((await request('/password','POST',{atual:'TesteSeguro123!',nova:'OutraSenha123!'})).status,200);assert.equal((await request('/logout','POST')).status,200);assert.equal((await request('/data')).status,401);});
});
